import {VEHICLES} from '../vehicles/VehicleCatalog.js';
export class HUD{
 constructor(root,track,onReturn){this.onReturn=onReturn;const raw=[];for(let i=0;i<120;i++){const p=track.curve.getPointAt(i/120);raw.push(p)}const xs=raw.map(p=>p.x),zs=raw.map(p=>p.z),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs),scale=Math.min(146/(maxX-minX),114/(maxZ-minZ)),ox=(160-(maxX-minX)*scale)/2,oy=(128-(maxZ-minZ)*scale)/2;this.points=raw.map(p=>({x:ox+(p.x-minX)*scale,y:oy+(p.z-minZ)*scale}));const path=this.points.map((p,i)=>`${i?'L':'M'}${p.x.toFixed(1)} ${p.y.toFixed(1)}`).join(' ')+' Z',finish=this.points[0],before=this.points[119],after=this.points[1],dx=after.x-before.x,dy=after.y-before.y,length=Math.hypot(dx,dy)||1,nx=-dy/length*7,ny=dx/length*7,opponents=Array.from({length:5},(_,i)=>`<circle id="opponent-${i}" r="3.1" fill="#ff7658" stroke="#fff" stroke-width="1"/>`).join('');this.el=document.createElement('div');this.el.className='hud';this.el.innerHTML=`<div id="countdown" class="countdown">3</div><div class="race"><b><span id="pos">6</span><small> / 6</small></b><label>POSIÇÃO</label><div class="lap"><span>VOLTA</span> <b id="lap">1/3</b></div><div id="time">00:00.000</div></div><div class="speed"><b id="speed">000</b><span>KM/H</span><i><em id="bar"></em></i></div><div class="map"><svg viewBox="0 0 160 128" width="160" height="128"><path d="${path}" fill="none" stroke="rgba(255,255,255,.7)" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><line x1="${finish.x-nx}" y1="${finish.y-ny}" x2="${finish.x+nx}" y2="${finish.y+ny}" stroke="#fff" stroke-width="3"/><line x1="${finish.x-nx}" y1="${finish.y-ny}" x2="${finish.x+nx}" y2="${finish.y+ny}" stroke="#181818" stroke-width="1" stroke-dasharray="2 2"/>${opponents}<circle id="dot" r="4" fill="#60efa0" stroke="#fff" stroke-width="1.5"/></svg></div><div class="goal"><small>OBJETIVO</small><b>TERMINE EM 3º</b><hr><small>DESAFIO</small><strong>VOLTA RÁPIDA</strong></div><div class="tip">WASD / SETAS · ESPAÇO FREIO DE MÃO · G DEBUG</div><div id="fps"></div>`;root.append(this.el)}
 configure(total,laps){this.laps=laps;this.el.querySelector('.race>b small').textContent=' / '+total;const svg=this.el.querySelector('.map svg');svg.querySelectorAll('[id^="opponent-"]').forEach(m=>m.remove());for(let i=0;i<total-1;i++){const c=document.createElementNS('http://www.w3.org/2000/svg','circle');c.id='opponent-'+i;c.setAttribute('r','3');c.setAttribute('fill','#ff7658');c.setAttribute('stroke','white');svg.insertBefore(c,svg.querySelector('#dot'));}this.el.querySelector('#countdown').textContent='CARREGANDO';}

 setQualifying(active){
  this.el.querySelector('.race label').textContent=active?'CLASSIFICAÇÃO':'POSIÇÃO';
  this.el.querySelector('.race>b').style.display=active?'none':'';
  this.el.querySelector('.lap').style.display=active?'none':'';
  this.el.querySelectorAll('[id^="opponent-"]').forEach(m=>m.style.display=active?'none':'');
  this.el.querySelector('.goal b').textContent=active?'DEFINA SEU LUGAR NO GRID':'TERMINE EM 3º';
  this.el.querySelector('.goal strong').textContent=active?'CRUZE A LINHA PARA INICIAR':'VOLTA RÁPIDA';
 }
 showQualifying(order,ai,onStart){
  const time=t=>Math.floor(t/60)+':'+(t%60).toFixed(3).padStart(6,'0');
  const overlay=document.createElement('div');overlay.className='finish-screen';
  overlay.innerHTML='<small>CLASSIFICAÇÃO CONCLUÍDA</small><h2 class="qualifying-title">GRID DE LARGADA</h2><ol class="qualifying-results"></ol><small>TEMPOS DOS OPONENTES SIMULADOS</small><button type="button">INICIAR CORRIDA</button>';
  order.forEach((e,i)=>{const li=document.createElement('li');li.className=e.id==='player'?'you':'';const name=e.id==='player'?'VOCÊ':VEHICLES[ai[e.id].modelId].name;li.textContent=(i+1)+'º · '+name+' — '+time(e.time);overlay.querySelector('ol').append(li);});
  overlay.querySelector('button').onclick=()=>{overlay.remove();onStart();};this.el.parentElement.append(overlay);
 }

 setLoadingError(onReturn){const overlay=document.createElement('div');overlay.className='finish-screen';overlay.innerHTML='<h2>ERRO AO CARREGAR</h2><button>VOLTAR À GARAGEM</button>';overlay.querySelector('button').onclick=onReturn;this.el.parentElement.append(overlay);}
 setCountdown(value){const el=this.el.querySelector('#countdown');if(value<-.35){el.classList.add('hidden');return}el.classList.remove('hidden');el.textContent=value<=0?'VAI!':Math.max(1,Math.ceil(value));el.classList.toggle('go',value<=0)}
 showFinish(position,time){const m=Math.floor(time/60),s=(time%60).toFixed(3).padStart(6,'0'),overlay=document.createElement('div');overlay.className='finish-screen';overlay.innerHTML=`<small>RESULTADO FINAL</small><h2>${position}º LUGAR</h2><p>${String(m).padStart(2,'0')}:${s}</p><button type="button">VOLTAR À GARAGEM</button>`;overlay.querySelector('button').addEventListener('click',()=>this.onReturn?.(),{once:true});this.el.parentElement.append(overlay)}
 update(speed,pos,lap,time,t,debug,fps,opponentTs=[]){this.el.querySelector('#speed').textContent=String(Math.round(Math.abs(speed)*3.6)).padStart(3,'0');this.el.querySelector('#bar').style.width=Math.min(100,Math.abs(speed)/44*100)+'%';this.el.querySelector('#pos').textContent=pos;this.el.querySelector('#lap').textContent=`${lap}/${this.laps||3}`;const m=Math.floor(time/60),s=time%60;this.el.querySelector('#time').textContent=`${String(m).padStart(2,'0')}:${s.toFixed(3).padStart(6,'0')}`;const p=this.points[Math.floor(t*this.points.length)%this.points.length],d=this.el.querySelector('#dot');d.setAttribute('cx',p.x);d.setAttribute('cy',p.y);opponentTs.forEach((value,i)=>{const q=this.points[Math.floor(value*this.points.length)%this.points.length],marker=this.el.querySelector(`#opponent-${i}`);if(marker){marker.setAttribute('cx',q.x);marker.setAttribute('cy',q.y)}});this.el.querySelector('#fps').textContent=debug?`${fps} FPS · DEBUG`:''}
}
