import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {daylightEnvironment} from '../world/RenderPolish.js';
import {VEHICLES as defaultVehicles,loadVehicleModel as defaultLoadVehicle} from '../vehicles/VehicleCatalog.js';
import '../menu.css';
import {CIRCUITS} from '../world/Circuits.js';
const defaultPaints=[['Original','#ffffff'],['Terracotta','#ce6c39'],['Pearl','#f1ede5'],['Racing red','#bc302a'],['Sunset','#db872b'],['Atlantic','#225781'],['Graphite','#303941'],['Forest','#345747']];
export function showMainMenu(root,options={}){return new Promise(resolve=>{
 const VEHICLES=options.vehicles||defaultVehicles,loadVehicleModel=options.loadVehicle||defaultLoadVehicle;
 const paints=options.illustrated?[['Original','#ffffff'],['Coral','#ee654c'],['Verde','#49af71'],['Azul','#428cd8'],['Amarelo','#f3be3e'],['Violeta','#a477d8']]:defaultPaints;
 let selected=options.illustrated?'defender':'renegade',color=paints[0][1],model,running=true,token=0,ready=false;
 const menu=document.createElement('section');menu.className='garage';
 menu.innerHTML=`<header><a class="garage-logo">SUV<span> CHALLENGE</span></a><span>SUV CHALLENGE · TOUR</span></header><div class="garage-layout"><section class="garage-view"><div class="garage-caption"><small>GARAGEM / 01</small><h1></h1><p>Arraste para explorar seu carro.</p></div><canvas aria-label="Prévia interativa do carro"></canvas><div class="garage-status" role="status">Carregando veículo…</div></section><aside><small>ESCOLHA SEU CARRO</small><div class="garage-cars"></div><div class="paint-heading">PINTURA <span class="paint-name">Pearl</span></div><div class="garage-paints"></div><dl class="garage-specs"></dl><label class="race-options">CIRCUITO<select id="circuit-choice"></select></label><p id="circuit-description"></p><label class="race-options">PILOTOS<select id="racer-choice"><option value="2">2 · Corrida de 1 volta</option><option value="6">6 · Corrida</option><option value="10">10 · Grid completo</option></select></label><button class="garage-start" disabled>CARREGANDO…</button></aside></div><footer><span>WASD / SETAS · DIRIGIR</span><span>ESPAÇO · FREAR</span><span>SHIFT · TURBO</span><span>G · INSPECIONAR</span></footer>`;
 root.append(menu);const circuits=menu.querySelector('#circuit-choice');for(const[id,c]of Object.entries(CIRCUITS)){if(options.illustrated&&id!=='city')continue;const o=document.createElement('option');o.value=id;o.textContent=options.illustrated?'São Paulo · Edição Ilustrada':c.name;circuits.append(o);}circuits.onchange=()=>menu.querySelector('#circuit-description').textContent=options.illustrated?'Cidade em tons pastel · classificação e corrida':CIRCUITS[circuits.value].description;circuits.onchange();
 const credits=document.createElement('details');credits.style.cssText='position:absolute;bottom:55px;left:24px;z-index:5;max-width:75%;background:#172026;color:#eee;padding:8px;font-size:12px';credits.innerHTML='<summary>Créditos dos SUVs adicionados</summary><p>Modelos distribuídos por free-3d.fr · <a href="https://creativecommons.org/licenses/by/3.0/fr/" target="_blank" rel="noopener">CC BY 3.0 FR</a>. Escala, orientação e materiais adaptados; texturas originais.</p><a href="https://www.free-3d.fr/model/modele-3d-gratuit-suv-tout-terrain-duster-18023" target="_blank" rel="noopener">Duster</a> · <a href="https://www.free-3d.fr/model/suv-moderne-3d-gratuit-type-tout-terrain-75560" target="_blank" rel="noopener">Modern Off-road</a> · <a href="https://www.free-3d.fr/model/modele-3d-gratuit-suv-compact-orange-moderne-93757" target="_blank" rel="noopener">Orange Compact</a>';credits.insertAdjacentHTML('beforeend','<p>Jeep Renegade 2016 — <a href="https://sketchfab.com/3d-models/jeep-renegade-2016-192f7e81dce84c6780434f692a0f96c5" target="_blank" rel="noopener">Jose Bronze</a>; Police SUV — <a href="https://sketchfab.com/3d-models/lowpoly-generic-suv-police-259fc16c23d548ba8d5802c563d8ebdc" target="_blank" rel="noopener">mk2design</a>. <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a>. Escala adaptada; sombra da polícia removida. Hummer H3: arquivo fornecido pelo usuário, licença não verificada; geometria simplificada.</p>');menu.append(credits);
 if(options.illustrated)credits.innerHTML='<summary>Créditos · edição ilustrada</summary><p>Veículos low-poly: ilkhom23 / CGTrader, pack fornecido pelo usuário, licença original. Ônibus e van: Raphael Gonçalves / Rgsdev, CC0, Free Low Poly Vehicles Pack. Defender: crédito original do projeto. Escala e materiais adaptados; texturas UV preservadas.</p>';
 const canvas=menu.querySelector('canvas'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,1,.1,100);camera.position.set(6,2.9,6);
 const controls=new OrbitControls(camera,canvas);controls.target.set(0,.9,0);controls.enablePan=false;controls.minDistance=4;controls.maxDistance=11;controls.maxPolarAngle=Math.PI/2-.03;controls.enableDamping=true;controls.autoRotate=true;controls.autoRotateSpeed=.5;
 const env=daylightEnvironment(renderer);scene.environment=env.texture;
 scene.add(new THREE.HemisphereLight(0xe1efff,0x414535,1.2));
 const sun=new THREE.DirectionalLight(0xffe0b7,3);sun.position.set(-5,8,5);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);
 const floor=new THREE.Mesh(new THREE.CircleGeometry(12,64),new THREE.MeshStandardMaterial({color:0x222c31,roughness:.8}));floor.rotation.x=-Math.PI/2;floor.position.y=-.01;floor.receiveShadow=true;scene.add(floor);
 if(options.illustrated){scene.environment=null;renderer.toneMapping=THREE.NoToneMapping;sun.intensity=1.3;scene.children.filter(o=>o.isHemisphereLight).forEach(o=>o.intensity=.65);floor.material.color.set('#dedbcc');}
 const composer=options.createComposer?.(renderer,scene,camera);
 const resize=()=>{const rect=canvas.getBoundingClientRect();renderer.setSize(Math.max(1,rect.width),Math.max(1,rect.height),false);composer?.setSize(Math.max(1,rect.width),Math.max(1,rect.height));camera.aspect=rect.width/Math.max(1,rect.height);camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(canvas);resize();
 const status=menu.querySelector('.garage-status'),start=menu.querySelector('.garage-start');menu.querySelector('.paint-name').textContent=paints[0][0];
 const refresh=async()=>{const request=++token,v=VEHICLES[selected];ready=false;start.disabled=true;status.textContent='Carregando veículo…';menu.querySelector('h1').textContent=v.name;menu.querySelector('.garage-specs').innerHTML=`<div><dt>VELOCIDADE</dt><dd>${Math.round(v.topSpeed*3.6)} km/h</dd></div><div><dt>CLASSE</dt><dd>${v.className}</dd></div>`;
 try{const next=await loadVehicleModel(selected,parseInt(color.slice(1),16));if(!running||request!==token)return;for(const m of next.userData.paintMaterials)m.color.set(color);options.styleModel?.(next);if(model)scene.remove(model);model=next;scene.add(model);ready=true;menu.querySelectorAll('.garage-paints button').forEach(b=>b.disabled=!next.userData.paintMaterials.length);menu.querySelector('.paint-name').textContent=next.userData.paintMaterials.length?(paints.find(p=>p[1]===color)?.[0]||''):'Original';status.textContent=next.userData.paintMaterials.length?'':'Pintura original neste modelo';start.textContent='INICIAR CLASSIFICAÇÃO →';start.disabled=false;}catch(e){status.textContent='Não foi possível carregar. Selecione outro carro.';console.error(e)}};
 for(const[id,v]of Object.entries(VEHICLES)){const b=document.createElement('button');b.textContent=v.name;b.className=id===selected?'selected':'';b.onclick=()=>{selected=id;menu.querySelectorAll('.garage-cars button').forEach(x=>x.classList.toggle('selected',x===b));refresh()};menu.querySelector('.garage-cars').append(b)}
 for(const[name,value]of paints){const b=document.createElement('button');b.style.background=value;b.setAttribute('aria-label',name);b.className=value===color?'selected':'';b.onclick=()=>{color=value;menu.querySelector('.paint-name').textContent=name;menu.querySelectorAll('.garage-paints button').forEach(x=>x.classList.toggle('selected',x===b));if(options.illustrated){refresh();return;}if(model)for(const m of model.userData.paintMaterials)m.color.set(value)};menu.querySelector('.garage-paints').append(b)}
 let timeChoice=null;if(options.illustrated){const label=document.createElement('label');label.className='race-options';label.textContent='HORÁRIO';timeChoice=document.createElement('select');timeChoice.innerHTML='<option value="day">Dia · garoa durante a corrida</option><option value="night">Noite · garoa durante a corrida</option>';label.append(timeChoice);start.before(label);}
 let raf;const draw=()=>{if(!running)return;raf=requestAnimationFrame(draw);controls.update();if(composer)composer.render();else renderer.render(scene,camera)};draw();
 start.onclick=()=>{if(!ready)return;running=false;++token;cancelAnimationFrame(raf);observer.disconnect();controls.dispose();env.dispose();composer?.dispose();renderer.dispose();const racers=Number(menu.querySelector('#racer-choice').value);menu.remove();resolve({timeOfDay:timeChoice?.value||'day',circuit:circuits.value,id:selected,color:parseInt(color.slice(1),16),stats:VEHICLES[selected],racers,laps:racers===2?1:3})};
 refresh();
})}
